### PR TITLE
Add UIView TemporaryPositionAndDimensions extension

### PR DESCRIPTION
**Pull request by JanNash**
Blocked by: 
- [x] ~#65~
- [x] ~resmio/SignificantSpices#8~

### CODE REVIEW

**Comment by JannKleen** [comment]
@JanNash CircleCI is failing and it's not blocked by #65 anymore

**Comment by JanNash** [comment]
Yes, it's still blocked by a Spices PR which I had forgotten to create :/. Updated the info above and created the PR.

**Comment by JanNash** [comment]
@JannKleen unblocked

**Comment by JannKleen** [comment]
I feel like `UIView (TemporaryPositionAndDimensions).swift` needs some more comments

**Comment by JanNash** [comment]
Agreed. I will make it so.

**Comment by JanNash** [comment]
@JannKleen I've added some documentation, but I'm still open to suggestions.

**Pull request merged**
